ftclib/src/main/java/com/arcrobotics/ftclib/hardware/SensorTOFDistance.java
Adds full class for Time-of-flight distances sensor including distance targets, and device-specific lists of targets. No errors :)
It includes the following:
-bad javadoc(lol)
-methods supporting directly reading distance sensor
-distance target mechanism
-ability to check for atTarget
-ability to give distance sensor multiple distance targets
- ability to check all targets at once and return the results (in progress because undecided whether it should return a HashMap<String, DistanceTarget>  with results or another way.)
-add target at any time
-Distance target:
-user given name
-user given value
-user given unit
-throws IllegalArguementException if value is more than 2m (undecided whether this limit should be a user set one)
-can change name, unit or value at any time
Also should …
=> Time-Of-Flight Distance Sensor Class

CONTRIBUTING.md
Updated CONTRIBUTING.md to use lower-case commit prefixes instead of title-case
=> docs(CONTRIBUTING): update to fix commit prefixes

brand/logo/black/FTCLib-black.svg, brand/logo/color/FTCLib.svg, brand/logo/grayscale/FTCLib-grayscale.svg
Rectangles to circles, hopefully. Haven't tested in Safari yet but I'm assuming it at least supports specifying the radius in CSS.
=> fix: SVG logo in Safari

core/build.gradle, core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java, core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorEx.java, readme.md
* Fix - fixes #112 ; uses `super()` in the constructor and pre-initializes default controllers
* No
=> MotorEx Calls Super At Constructor

core/src/main/java/com/arcrobotics/ftclib/util/LUT.java, core/src/test/java/com/arcrobotics/ftclib/util/LUTTest.java
This is a pretty small PR. The existing implementation does a linear search through all the entries in the map to find the closest key, which wastes all the benefits of using a map. This changes it to use a TreeMap, so finding the closest entry can be done in logarithmic time.
* Fix - Improved performance
* Feature - Added LUT unit test
* No, it doesn't change the contract of LUT, it just improves the performance
=> Improve LUT

core/src/main/java/com/arcrobotics/ftclib/util/Timing.java, core/src/test/java/com/arcrobotics/ftclib/util/TimingTest.java, examples/src/main/java/com/example/ftclibexamples/OldCommandSample/SimpleLinearLift.java
The timer class seemed to be broken. The `ElapsedTime` class has pretty ambiguous documentation, so the `Timer` class wasn't using it correctly. This meant that a lot of the behavior of the timer class was incorrect. The pause and resume functionality was incorrect, and so was the functionality to track elapsed time.
The `currentTime()` method was a little ambiguous as well (is it counting up from 0, or counting down from `timerLength`?) so I renamed it to `elapsedTime()` and added a `remainingTime()`.
* Fix
* Feature
* Unless some code relied on broken behavior, this shouldn't break anything
=> Fix timer bugs

core/src/test/java/com/arcrobotics/ftclib/command/CommandSchedulerTests.java, core/vision/build.gradle, readme.md
* Other - change version of EOCV to v1.4.2
I also changed the vision version from 1.1.0 to 1.2.0 for the next release.
Not for FTCLib - all changes can be found in the [EOCV changelog](https://github.com/OpenFTC/EasyOpenCV#v142).
=> Change EOCV Version to 1.4.2

core/src/main/java/com/arcrobotics/ftclib/gamepad/ButtonReader.java, core/src/main/java/com/arcrobotics/ftclib/gamepad/GamepadEx.java, core/src/main/java/com/arcrobotics/ftclib/gamepad/TriggerReader.java, core/src/main/java/com/arcrobotics/ftclib/hardware/ServoEx.java, core/src/test/java/com/arcrobotics/ftclib/gamepad/GamepadButtonTest.java, examples/src/main/java/com/example/ftclibexamples/GamepadSample.java
* Feature - makes the use of readers more efficient to use only one value read per loop (reverts the change made in #109) and adds a single `readButtons()` method to `GamepadEx` to read all button values at once
* No
=> Revert Value Reading and Add Read Method to GamepadEx

core/src/test/java/com/arcrobotics/ftclib/util/TimingTest.java
* Fix - the issue was the thread was slept for 1 second but the timer might not have reached that 1 second mark yet when the timer is then paused. When calling `.elapsedTime()` this will return 0 because the timer is in seconds, which returns a long. Since it is less than 1, it was truncated to 0, so it was not `>= 1`. So, I increased the sleep time by 5 milliseconds to ensure the timer pauses at that point.
* No
=> Fix Pause Test For Timer

core/build.gradle, core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java
After testing the target distance calculation, there was a mistake in the math. It should have been multiplying by distance per pulse instead of dividing, to get the correct distance target. Since the target position method uses the target distance method, tracking whether the target is distance or not is useless.
* Fix
* No
=> Fix Target Position For Non-Default Distance Per Pulse

core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java, core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorEx.java
* Feature
Adds a buffer to the motors for velocity PID mode.
In `MotorEx`, setting the velocity now calls `set()` and `set()` calls `setPower()` for `VelocityControl`.
Streamlines the constructors and sets the RPM and CPR of the motor in the configuration type for the third constructor.
* No
=> Improve MotorEx Velocity and Motor Configuration Type

core/src/main/java/com/arcrobotics/ftclib/hardware/SimpleServo.java
* Fix
As @JIceberg pointed out, it seems that AngleUnit methods perform a -180 to 180 normalization which can be a problem for servos which go from beyond that limit. There’s a workaround way for fixing this by doing a range of i.e -90 to 180 degrees for a servo with a range of 0 to 270 (like the rev servos), but it’s less intuitive for the user, which is the reason for this internal change.
This PR uses a custom internal method to perform the conversions with the AngleUnit enum without the mentioned normalization.
* No
=> Remove normalization from AngleUnit in SimpleServo

core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGContourRingPipeline.kt
* Feature
Added getRectWidth, getRectHeight, and getRectSize methods in UGContourRingPipeline.kt to expose the width, height, and size of the bounding box around the rings when created with the vision pipeline. 
_Please note this is my first pull request and I am fairly new to open source._
* No
=> Added getRectWidth, getRectHeight, and getRectSize methods in UGContourRingPipeline.kt

core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java
* Fix - changes the way the multiplier is engaged so the resetVal is independent of that flip in direction
* No
=> Fix Reset Encoder on Reversed Direction

core/build.gradle, core/dependencies.gradle
Updates the SDK version from 6.2 (maven migrate) to 7.0 (Freight Frenzy seasonal release)
* Feature
Depends - on the user end, this should not impact anything. On our end, there might be something changed in the SDK that does in fact produce a breaking change.
=> Update SDK Dependencies

core/src/main/java/com/arcrobotics/ftclib/hardware/SimpleServo.java
Fix: min and max arguments flipped on call to constructor. 
Codestyle: Consider renaming parameter to minDegree and maxDegree to clarify to caller that AngleUnit.DEGREES is assumed.
* Fix
* Codestyle
* No
=> Min and Max flipped. Clarify AngleUnit type in parameter name

core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java, core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorGroup.java
* Feature
This PR improves upon the motor velocity obtained from the built-in encoder class. The inversion meaning of the `MotorGroup` class has been changed to better suit these changes. `Motor.Encoder` now offers a `getRate()` method which returns the velocity of the encoder in units of distance per second, which is dependent on the defined distance per pulse. By default this is 1, so the output is typically in ticks per second.
* Yes, please list breaking changes
The breaking changes are:
* change in inversion scheme for `MotorGroup`
* changes the output of `getVelocities()` in …
=> Introduce Rate Feature to Motor Encoders

core/src/main/java/com/arcrobotics/ftclib/hardware/RevIMU.java
* Feature
* No (?)
@NoahAndrews can probably answer if removing the logging will result in issues if the user was previously calling `startAccelerationIntegration()`.
Resolves #197 
=> Remove Acceleration from RevIMU

core/vision/build.gradle
The currently published version of FTCLib uses EasyOpenCV v1.5.1. This version is known not to work with FTC SDK 8.0 which is being used for this season. Updating this library would cause no breaking API changes except to support the new version of the SDK.
See OpenFTC/EasyOpenCV#50 for reference of the issue at hand. I can also confirm that this update works perfectly on our robot.
* Fix
* Yes
Once merged, this PR would make FTCLib incompatible with versions earlier than v8.0.0.
=> Update EasyOpenCV to v1.5.2 to work with SDK 8.0

core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java, core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorGroup.java
* Feature
The current motor wrapper doesn't allow for a hard reset of the hardware position, which can lead to potential problems and as of now the only solution is to call to the available DcMotor and perform a STOP_AND_RESET. This should be an existing feature instead.
* No
=> Add Hard Encoder Reset

core/src/main/java/com/arcrobotics/ftclib/command/CommandBase.java
=> Fix `getName` in `CommandBase`
