FTCLib/FTCLib

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This will help standardize code contributions, branch naming, and commit naming.
> Create CONTRIBUTING.md and CODE_OF_CONDUCT.md

- ftclib/src/main/java/com/arcrobotics/ftclib/drivebase/HDrive.java
- ftclib/src/main/java/com/arcrobotics/ftclib/drivebase/RobotDrive.java
HDrive class created and mostly done. Working on field centric drive, currently missing math. Edited MotorType enum to add the kSlide variable.
> Added HDrive class and edited MotorType

- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/MecanumOdometrySample/FTCLibCommandSample/DriveSubsystem.java
- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/MecanumOdometrySample/FTCLibCommandSample/Teleop.java
- ftclib/src/main/java/com/arcrobotics/ftclib/hardware/GyroEx.java
- ftclib/src/main/java/com/arcrobotics/ftclib/hardware/JSTEncoder.java
- ftclib/src/main/java/com/arcrobotics/ftclib/hardware/RevIMU.java
- ftclib/src/main/java/com/arcrobotics/ftclib/hardware/motors/SimpleMotorImpl.java
- jst external encoder class
- added absolute heading to gyro
> Feat: added odometry examples

- build.gradle
- ftclib/build.gradle
- ftclib/src/main/java/com/arcrobotics/ftclib/Vision/ExamplePipeLine.java
- ftclib/src/main/java/com/arcrobotics/ftclib/Vision/InternalCameraExample.java
Added an more in depth example of a easyopencv pipeline.
> added vision examples

- readme.md
The readme can now be seen from the first page
> Copied over readme

- FtcLib/src/main/java/com/arcrobotics/ftclib/kinematics/ConstantVeloMecanumOdometry.java
So the center of the robot can actually be the center of the robot
> Adds the center wheel offset to constant velo mecanum odometry

- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/DecelerationController.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/Path.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/PathMotionProfile.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/PurePursuitUtil.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/Waypoint.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/actions/InterruptAction.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/actions/TriggeredAction.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/types/PathType.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/types/WaypointType.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/waypoints/EndWaypoint.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/waypoints/GeneralWaypoint.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/waypoints/InterruptWaypoint.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/waypoints/PointTurnWaypoint.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/waypoints/StartWaypoint.java
Added files for pure pursuit functionality. Readme is unchanged.
> Added pure pursuit files.

- CONTRIBUTING.md
- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/SkystoneSample.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/SkystoneTest.java
- build.common.gradle
Signed-off-by: Jackson Isenberg <jisenberg1050@gmail.com>
> fix: eocv and multidex

- CONTRIBUTING.md
- FtcLib/src/main/java/com/arcrobotics/ftclib/kinematics/ConstantVeloMecanumOdometry.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/kinematics/DifferentialOdometry.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/kinematics/HolonomicOdometry.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/kinematics/Odometry.java
- FtcLib/src/main/java/com/arcrobotics/ftclib/purepursuit/Path.java
- FtcLib/src/test/java/com/arcrobotics/ftclib/ExampleUnitTest.java
- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/SkystoneSample.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OpModes/SkystoneTest.java
- build.common.gradle
* New feature
* Yes, the breaking change is rehashing the Odometry interface.
* However, it is able to merge automatically
> create functional interfacing for odometry

- FtcRobotController/build.gradle
> update eocv dependency

- .github/workflows/android.yml
__Please make sure your pull requests follow the basic principles of text as demonstrated below.__
Sample text: UwU, pwease merge mwy pwull reqwest into mwaster, senpai~!
For your PR, please make sure it answers the following:
* Fixie wixie
* New thingy wingy
* Stylish code uwu
* Refwactor
* Sowwy, something else~
* Yeppy yeppy! Sowwy, senpai!
* Not at all! owo
__Please make sure your PR satisfies the requirements of [the contributing page](./CONTRIBUTING.md)__
> fix gradlew

- readme.md
I introduced a fucky wucky update to the WEADME.
For your PR, please make sure it answers the following:
* WEADME Update
* Nopy wopy! IT witewally adds a single line to the WEADME.
> Add warning to README

- core/src/main/java/com/arcrobotics/ftclib/drivebase/DifferentialDrive.java
- core/src/main/java/com/arcrobotics/ftclib/drivebase/HDrive.java
- core/src/main/java/com/arcrobotics/ftclib/drivebase/MecanumDrive.java
- core/src/main/java/com/arcrobotics/ftclib/kinematics/DifferentialOdometry.java
- core/src/main/java/com/arcrobotics/ftclib/kinematics/HolonomicOdometry.java
- core/src/main/java/com/arcrobotics/ftclib/purepursuit/Path.java
- core/src/main/java/com/arcrobotics/ftclib/purepursuit/PurePursuitUtil.java
- core/src/test/java/com/arcrobotics/ftclib/controller/PIDInputOutputTest.java
- core/src/test/java/com/arcrobotics/ftclib/controller/ProfiledPIDControllerTest.java
- core/src/test/java/com/arcrobotics/ftclib/controller/RamseteControllerTest.java
- core/src/test/java/com/arcrobotics/ftclib/geometry/Pose2dTest.java
- core/src/test/java/com/arcrobotics/ftclib/purepursuit/UtilTest.java
- examples/src/main/java/com/example/ftclibexamples/InterpLUTSample.java
- examples/src/main/java/com/example/ftclibexamples/LookUpTableSample.java
- examples/src/main/java/com/example/ftclibexamples/SharedOdometry/AutoStaticRobotPose.java
- examples/src/main/java/com/example/ftclibexamples/SharedOdometry/TeleStaticRobotPose.java
> merge feat-odometry

- core/build.gradle
- core/src/main/java/com/arcrobotics/ftclib/geometry/Transform2d.java
- core/src/test/java/com/arcrobotics/ftclib/geometry/Pose2dTest.java
- core/src/test/java/com/arcrobotics/ftclib/geometry/Rotation2dTest.java
- core/src/test/java/com/arcrobotics/ftclib/geometry/Transform2dTest.java
- core/src/test/java/com/arcrobotics/ftclib/geometry/Translation2dTest.java
- core/src/test/java/com/arcrobotics/ftclib/geometry/Twist2dTest.java
> Creating Geometry Tests

- core/build.gradle
- core/src/main/java/com/arcrobotics/ftclib/kinematics/Odometry.java
- examples/src/main/java/com/example/ftclibexamples/PurePursuitSample.java
* Fix
* No
This is a minor update that doesn't actually affect anything internal. It is simply a small bugfix that went unnoticed. @JarnaChao09 can you review this PR?
> Bugfix: Update Odometry To Update the Pose Upon Rotation

- core/src/main/java/com/arcrobotics/ftclib/command/PrintCommand.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorEx.java
> Rebase Dev to Master Following Hotfix

- core/build.gradle
- core/src/main/java/com/arcrobotics/ftclib/command/PrintCommand.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorEx.java
- examples/build.gradle
- readme.md
Yeah, I have no idea when v1.2.0 will actually be released, but I know for a fact that's the next dev version. I'm thinking it should be released with v1.2.0 of vision since we're adding the goal detection for that (and the versions will actually match!).
* Feature - I just changed the version number in the gradle file and readme
* No
> Change Version in Gradle to v1.2.0

- core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGContourRingDetector.kt
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGContourRingPipeline.kt
What kind of change does this PR introduce?
Fix / Feature
Did this PR introduce a breaking change?
No
> feat: add UGContourRingDetector

- core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGAdvancedHighGoalPipeline.java
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGAngleHighGoalPipeline.java
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/UGBasicHighGoalPipeline.java
* Feature
I don't believe so...
See closed PR for an explanation of the functionality of the code: https://github.com/FTCLib/FTCLib/pull/101
> Pulled from dev branch and readded changes

- core/build.gradle
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorEx.java
- readme.md
> MotorEx Velocity Hotfix

- core/src/main/java/com/arcrobotics/ftclib/geometry/Vector2d.java
What kind of change does this PR introduce?
Fix - fix the vector project math
Did this PR introduce a breaking change?
No
> fix: vector projection formula

- core/src/main/java/com/arcrobotics/ftclib/hardware/ServoEx.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/SimpleServo.java
- examples/src/main/java/com/example/ftclibexamples/GamepadSample.java
- examples/src/main/java/com/example/ftclibexamples/OldCommandSample/Auto.java
* Refactor/Feature (testing pending)
* Yes, please list breaking changes
- rotateDegrees() method renamed to rotateAngle()
- removed constructors without min and max angle parameters, for forcing user to enter the range manually which is dependent on the servo they use (per suggestion from @dansman805)
- changed constructor param order from max, min to min, max since it makes more sense to have that order.
> Adds AngleUnit into Servo wrapper

- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/CRServo.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorEx.java
* Feature - allow the user to input a target distance rather than just a target position in ticks
* Feature - better velocity control in Motor/MotorEx
* Fix - fix FLOAT to actually produce DcMotor.ZeroPowerBehavior.FLOAT
* No
> MotorEx/Motor PID Mode Improvement

- core/src/main/java/com/arcrobotics/ftclib/command/RunCommand.java
- core/src/test/java/com/arcrobotics/ftclib/command/CommandSchedulerTests.java
* Feature - add `RunCommand` from WPILib
* No
> Add RunCommand

- core/build.gradle
- core/dependencies.gradle
- examples/build.gradle
* Refactor (?
Addresses #147 
* Seems like new version didn't introduce any breaking change so it will most likely be fine
> Bump all FTC SDK dependencies to 6.1.1

- core/src/main/java/com/arcrobotics/ftclib/hardware/RevIMU.java
* Fix - uses a single hardware call to return the orientation as a 3-length double array for `getAngles()`
* No
> Fix IMU Efficiency

- core/src/main/java/com/arcrobotics/ftclib/kotlin/extensions/gamepad/GamepadExExt.kt
- core/src/main/java/com/arcrobotics/ftclib/kotlin/extensions/hardware/SimpleServoExt.kt
- examples/build.gradle
- examples/src/main/java/com/example/ftclibexamples/VisionSample/UGContourRingPipelineJavaExample.java
- examples/src/main/java/com/example/ftclibexamples/VisionSample/UGContourRingPipelineKtExample.kt
- examples/src/main/java/com/example/ftclibexamples/kotlinexamples/GamepadExExtSamples.kt
- examples/src/main/java/com/example/ftclibexamples/kotlinexamples/GeometryExtSample.kt
- examples/src/main/java/com/example/ftclibexamples/kotlinexamples/InterpLUTExtSample.kt
- examples/src/main/java/com/example/ftclibexamples/kotlinexamples/LUTExtSample.kt
- examples/src/main/java/com/example/ftclibexamples/kotlinexamples/RobotDriveExtSample.kt
- examples/src/main/java/com/example/ftclibexamples/kotlinexamples/SimpleServoExtSample.kt
* Feature - adds gamepad extensions in Kotlin
* No
> Gamepad Extensions for Kotlin

- core/src/main/java/com/arcrobotics/ftclib/hardware/RevIMU.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/SensorColor.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/SensorDistance.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/SensorDistanceEx.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/SensorRevTOFDistance.java
* Fix - fixed the constructor of `SensorColor` to use the actual name argument
* Codestyle - reformatted and styled the comments and classes for the sensors
* No
> Fix Sensor Styling and Invalid Logic

- examples/src/main/java/com/example/ftclibexamples/VisionSample/UGContourRingDetectorSample.java
- examples/src/main/java/com/example/ftclibexamples/VisionSample/UGRectRingVisionSample.java
* Feature - simple contour detector sample
* Refactor - moved rect sample to vision package
* No
> Add Contour Detector Sample

- core/vision/build.gradle
- examples/src/main/java/com/example/ftclibexamples/UGRectRingVisionSample.java
- readme.md
> Fix Merge Conflicts Between Dev and Master

- core/vision/build.gradle
> Bump EOCV to Latest Version for SDK 6.1

- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorEx.java
> Add Comments, Improve Encoder Methods, Add Acceleration to Motor/MotorEx

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- readme.md
> Update the Contributing Guide and README

- core/src/main/java/com/arcrobotics/ftclib/drivebase/DifferentialDrive.java
- core/src/main/java/com/arcrobotics/ftclib/drivebase/MecanumDrive.java
> Add Method to Directly Control Motor Power

- examples/src/main/java/com/example/ftclibexamples/MecanumDrivingSample.java
* Fix
This PR fixes the mecanum sample that was useless for FTCLib. Before, it did weird things with vector-based input driving for autonomous which is not useful for the user-base. This instead shows how to create the mecanum drive object, how to interact with it in teleop, and the differences between field centric and robot centric. In the future, more samples for simple autonomous programs (time-based) might be useful especially as we advertise more to rookies.
N/A - This was a sample.
> Update Mecanum Sample

- build.common.gradle
- build.gradle
- core/build.gradle
- core/dependencies.gradle
- core/src/main/java/com/arcrobotics/ftclib/controller/PIDFController.java
- dependencies.txt
- examples/build.gradle
- gradle/wrapper/gradle-wrapper.properties
Fix -- Fixes a typi in the PIDF controller that made `totalError` not accumulate error over time.
No
> Fix Typo in `PIDFController` That Breaks I-Term Total Error

- core/src/main/java/com/arcrobotics/ftclib/gamepad/TriggerReader.java
This PR is a line moving fix.
No.
> fix: set last state before current state

- core/vision/src/main/java/com/arcrobotics/ftclib/vision/FFCapstoneDetector.java
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/FFCapstonePipeline.java
* Feature
This PR adds a pipeline and detector people can use in order to find the position of their capstones. The pipeline will look for the largest contour and return its center point. The detector will then determine the position of the objects based on the center points relative to their position on the screen.
* No
> Capstone Vision for 2021 Season

- core/src/main/java/com/arcrobotics/ftclib/geometry/Vector2d.java
* Feature
This PR adds a function to normalize vectors within Vector2d.
* No
> Vector2d Normalization

- core/build.gradle
- core/dependencies.gradle
- core/vision/build.gradle
- examples/build.gradle
- readme.md
> Update README and Dependencies for v2.0 Version

- build.gradle
- core/build.gradle
- core/dependencies.gradle
- core/src/main/java/com/arcrobotics/ftclib/hardware/SimpleServo.java
- core/vision/build.gradle
- examples/build.gradle
- readme.md
* Fixes issue with vision package (wrong ktx-core version)
* Fixes missing commit for switching max and min angle in `SimpleServo`
> Hotfix For 2.0 - Wrong KTX Core Version

- build.gradle
- core/build.gradle
- core/vision/build.gradle
- examples/build.gradle
> Update Kotlin Version

- core/src/main/java/com/arcrobotics/ftclib/kinematics/wpilibkinematics/SwerveModuleState.java
* Feature? - Swerve module optimization function from wpilib. replaced "var" with "Rotation2d" due to compilation issues. Was useful for creating swerve code, otherwise same as wpilib. It returns a swerve module state object with a new angle and motor power after running calulations with current angle to find the optimal direction. Important function for swerve kinematics
* No
> SwerveModuleState module optimization

- core/src/main/java/com/arcrobotics/ftclib/command/MecanumControllerCommand.java
* Fix
Like with `RamseteCommand`, this command was ported incorrectly which leads to incorrect behavior in `isFinished`, making it end before it even begins.
* No
> Fix Mecanum Controller Command

- core/src/main/java/com/arcrobotics/ftclib/controller/PIDFController.java
> Remove misplaced comment.

- build.gradle
- core/build.gradle
- core/src/main/java/com/arcrobotics/ftclib/command/MecanumControllerCommand.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/RevIMU.java
- core/src/main/java/com/arcrobotics/ftclib/kinematics/wpilibkinematics/SwerveModuleState.java
- core/vision/build.gradle
- examples/build.gradle
> Add Dev Changes to Master for v2.1.0

- core/build.gradle
- core/dependencies.gradle
- core/vision/build.gradle
- examples/build.gradle
Updated with some small fixes and bumps dependency version for the new season.
> Release v2.1.0

- core/src/main/java/com/arcrobotics/ftclib/gamepad/TriggerReader.java
* Feature
* No
This commit aims to add a custom threshold parameter for the TriggerReader function.
> Add TriggerReader Threshold

- core/vision/build.gradle
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/AprilTag2dPipeline.java
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/AprilTagDetector.java
- examples/src/main/java/com/example/ftclibexamples/VisionSample/AprilTagVisionSample.java
* Feature: This PR has the scope of introducing EasyOpenCV's AprilTag support to FTCLib. Same idea as #228 except the PR has been updated more frequently. Closes #226 
* Unknown: The code has yet to be tested, however, no errors occurred during compiling.
> AprilTag Feature Support

- core/src/main/java/com/arcrobotics/ftclib/hardware/SensorDistanceEx.java
> Fix atTarget in SensorDistanceEx

- core/build.gradle
- core/dependencies.gradle
- core/src/main/java/com/arcrobotics/ftclib/command/CommandBase.java
- core/src/main/java/com/arcrobotics/ftclib/command/RepeatCommand.java
- core/src/main/java/com/arcrobotics/ftclib/command/TrapezoidProfileCommand.java
- core/src/main/java/com/arcrobotics/ftclib/gamepad/TriggerReader.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/SensorDistanceEx.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorGroup.java
- core/vision/build.gradle
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/AprilTag2dPipeline.java
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/AprilTagDetector.java
- examples/build.gradle
- examples/src/main/java/com/example/ftclibexamples/VisionSample/AprilTagVisionSample.java
- readme.md
Core - v2.1.1
Vision - v2.1.0
Includes
* #222
* #230
* #234 
* #236 
* #237 
* #238
> Release v2.1.1

- core/build.gradle
- core/dependencies.gradle
- core/src/main/java/com/arcrobotics/ftclib/command/CommandBase.java
- core/src/main/java/com/arcrobotics/ftclib/command/RepeatCommand.java
- core/src/main/java/com/arcrobotics/ftclib/command/TrapezoidProfileCommand.java
- core/src/main/java/com/arcrobotics/ftclib/gamepad/TriggerReader.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/SensorDistanceEx.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/Motor.java
- core/src/main/java/com/arcrobotics/ftclib/hardware/motors/MotorGroup.java
- core/vision/build.gradle
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/AprilTag2dPipeline.java
- core/vision/src/main/java/com/arcrobotics/ftclib/vision/AprilTagDetector.java
- examples/build.gradle
- examples/src/main/java/com/example/ftclibexamples/VisionSample/AprilTagVisionSample.java
- readme.md
* Add TrapezoidProfileCommmand and RepeatCommand (#222)
* fix: Bumped eocv to 1.5.0 and fixed breaking changes
* fix: Changed the vision release version to 2.0.0
* fix: Better error handling of camera opening
* fix: Surrounded the callback with the lock
* feat: repeat and trapezoid profile command
- Added RepeatCommand
- Added TrapezoidProfileCommand
* Add TriggerReader Threshold (#230)
* Add TriggerReader Threshold
* Style update
* Removed redundant constructor
* Add Hard Encoder Reset (#234)
* AprilTag Feature Support (#236)
* Create AprilTag2dPipeline.java
* Update AprilTag2dPipeline.java
* Update build.gradle
* Fix outdated class name causing build fail
* Pipeline style update
* Added AprilTagDetector.java
* Added getDetection function
* Added getDetection function
* Removed …
> Merge v2.1.1 into Dev
